#!/bin/bash
# GoGit'er command line application

#======================================================================
# Shell options
#======================================================================
shopt -s -o errexit     # Fail on error
shopt -s -o nounset     # Fail on unset variables

#======================================================================
# Module handling
#======================================================================
# Root directory - used for loading modules
GGROOT=$(dirname $(realpath $0))

# List of imported modules
GG_MODULES=

# Set the debug variable to be empty
GGDEBUG=${GGDEBUG:-}

# Debug function - prints the debug messages to the console
debug()
{
    if [[ -n "$GGDEBUG" ]]
    then
        for msg in "$@"
        do
            # Print it in a colorful format
            echo -n "$(tput setaf 7)DEBUG: "
            echo -n "$(tput setaf 2)${BASH_SOURCE[1]#$GGROOT/}"
            echo -n "$(tput sgr0):"
            echo -n "$(tput setaf 3)${BASH_LINENO[0]} "
            echo -n "$(tput sgr0)"
            echo "$msg"
        done
    fi
}

# Function to import functionality from sub-functions
ggmod()
{
    local module="$GGROOT/lib/$1.bash"
    if [[ ! -r "$module" ]]
    then
        panic 1 "Cannot load module '$1'"
    fi

    debug "Adding module '$1'"
    source "$module"
    GG_MODULES="$GG_MODULES:$1"
}

ggmod core  # Must be the first - this module loads all core functionality
ggmod cli

#======================================================================
# Command line handling
#======================================================================
gg_parse_command_line "$@"
